defaults:
  - _default
  - _self_
  - proto: dknn

type: "ProtoCBM"
concept_from_logit: False
extra_dims: 0
bool: False
sigmoidal_prob: True
sigmoidal_extra_capacity: True
bottleneck_nonlinear: null
output_latent: False