defaults:
  - _default_celeba
  - _self_

name: "CELEBA_CEM"
n_classes: 256
n_concepts: 6

# Mateo's code specific
use_binary_vector_class: true
label_binary_width: 1
num_hidden_concepts: 2
label_dataset_subsample: 12
weight_loss: false


