defaults:
  - _default_celeba
  - _self_

name: "CELEBA_GENDERAGE_4000"
root_dir: ./data/CelebA_torch/
subset_file: ./data/CelebA/subsets/balanced_respecting/4000.pkl
n_classes: 4
n_concepts: 38

# normalizer config
x_mean: ${universal.x_mean}
x_std: ${universal.x_std}