defaults:
  - _default
  - _self_

name: "CUB_200_112"
root_dir: ${universal.data_path}/CUB200/
pkl_dir: ${universal.data_path}/CUB200/pkls/
n_classes: 200
n_concepts: 112

# normalizer config
x_mean: ${universal.x_mean}
x_std: ${universal.x_std}
