type: DKNN
k: 2
tau: 1.0
method: deterministic
num_samples: -1
similarity: euclidean
loss_type: sparse_weighted
loss_params:
  positive_weight: 1.0
  negative_weight: 1.0
  num_neighbour_agnostic: True  # Set to false to replicate older results before April 2024
max_neighbours: -1
