name: "CUB_200_312"
num_workers: 15
batch_size: 16
root_dir: ./data/CUB200/
pkl_dir: ./data/CUB200/pkl/
n_classes: 200
n_concepts: 312

# normalizer config
x_mean: ${universal.x_mean}
x_std: ${universal.x_std}