python protocbm/run_cub.py \
    --cub_dir ../data/CUB200/ \
    --pkl_dir ../data/CUB200/pkls/ \
    --batch_size 4 \
    --num_workers 0 \
    --n_concepts 312 \
    --x2c_arch resnet50 \
    --n_classes 200 \
    --max_epochs 100 \
    --tb_log_dir ../logs/protocbm/ \
    --tags "COMMIT:9c03a6" \
    --lr 0.001 \
    --epochs_proto_recompute 2
